### ISSUE TITLE
在android4.2的游览器发生错误,xhr.send的时候只发送了header，没有发送body

### ISSUE THREAD

**Issue by hokkoo** [aliyun-UED/oss-js-upload#1]
参考，https://ghinda.net/article/jpeg-blob-ajax-android/
参考事例：http://jsfiddle.net/ghinda/fRgbf/
将var frOnload = function (e) {
                    result.md5 = hexToBase64(SparkMD5.ArrayBuffer.hash(e.target.result));
                    callback(null, result);
                };
改为：
var frOnload = function (e) {
                    result.md5 = hexToBase64(SparkMD5.ArrayBuffer.hash(e.target.result));
                    result.blob = e.target.result;
                    callback(null, result);
                };
就能正常使用了。

**Comment by chylvina** [comment]
已经修复并发布，非常感谢你的反馈！
