### ISSUE TITLE
20 Nov 2015的oss-js-upload.js有小bug，已解决

### ISSUE THREAD

**Issue by leochan2017** [aliyun-UED/oss-js-upload#14]
第54行~59行，改成：

this.oss = new ALY.OSS({
        accessKeyId: this._config.stsToken.credentials.accessKeyId,
        secretAccessKey: this._config.stsToken.credentials.accessKeySecret,
        securityToken: this._config.stsToken.credentials.securityToken,
        endpoint: this._config.endpoint,
        apiVersion: '2013-10-15'
      });

**Comment by chylvina** [comment]
你好，能否提交一个 pull request
