### ISSUE TITLE
支持上传进度，取消上传

### ISSUE THREAD

**Issue by chylvina** [aliyun-UED/oss-js-upload#4]

**Comment by elaijuh** [comment]
这个功能什么时候加？

**Comment by CodeLYQ** [comment]
我用了一个笨方法实现了进度条。定义了一个全局变量 my_global_progress，修改代码：
xhr.upload.addEventListener('progress', function (evt) {
      emitter.emit('sendProgress', evt);
  });
改为：

xhr.upload.addEventListener('progress', function (evt) {
       my_global_progress = evt.loaded / evt.total;
      //  console.log(my_global_progress);
      emitter.emit('sendProgress', evt);
  });

目前暂时满足我自己的需求，不知道官方有没有更好的办法？有没有那里可以传一个回调函数进去专门处理上传进度？

**Comment by chylvina** [comment]
发布 0.5.0，支持上传进度。

**Comment by amnyx** [comment]
太好了，不需要自己扩展Process功能了，赞！

**Comment by amnyx** [comment]
阿里云的javascript sdk略大，压缩之后还要330KB左右，在web端用起来感觉太重了。
请问阿里云有没有压缩sdk体积的计划？

**Comment by jiangtao** [comment]
@Np0C 放在公有云上 就好了额。

**Comment by yaimeet** [comment]
进度支持了，取消好像没有啊，看官方文档，取消都是后端上传，前端sdk，没有取消API么？
