### ISSUE TITLE
GetFederation 接口什么时候能恢复？现在这个例子用不了

### ISSUE THREAD

**Issue by TonyLuo** [aliyun-UED/oss-js-upload#6]
oss-js-upload.js:54 Uncaught TypeError: Cannot read property 'AccessKeyId' of undefined

code: "UnknownError"
message: "Specified api is not found, please check your url and method."
retryable: false
statusCode: 404
time: "2015-09-12T11:06:09.600Z"

**Comment by chylvina** [comment]
代码更新，现在支持 sts 新的 assumeRole 方法
