### ISSUE TITLE
怎样支持  canvas形式处理后返回的base64数据 

### ISSUE THREAD

**Issue by roycms** [aliyun-UED/oss-js-upload#9]
用 https://github.com/fengyuanchen/cropper 插件处理后的图片怎样通过oss-js-upload 发出请求？
期待您的回答

**Comment by CodeLYQ** [comment]
处理后的图片是base64字符串？如果是，我试过将它上传到OSS.

**Comment by chylvina** [comment]
是的，可以上传 base65 字符串。

**Comment by CodeLYQ** [comment]
之前试过上传base64字符串，但不成功（也许我处理的不对），但是将base64转为blob或者arraybuffer，我现在是转为arraybuffer再上传的，pc端和移动端都没问题的。

**Comment by chylvina** [comment]
很好，谢谢。

**Comment by joeylin** [comment]
这个插件可以这么用，图片上传之后，直接调用oss的图片处理接口，亲测过，这个插件的实现的图片处理功能，oss的后台的处理功能都支持。查阅：https://docs.aliyun.com/#/pub/oss/oss-img-api/intruduction&brief

**Comment by CodeLYQ** [comment]
@joeylin 赞哦！正需要这个。

**Comment by hochiminh1988** [comment]
@phoue 现在刚好需要这个功能，请问有网站或者代码共享吗？谢谢！
